# Generated by Django 4.2.7 on 2025-12-08 07:37

from django.db import migrations, models
import storage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=storage.models.user_directory_path)),
                ('size', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('share_link', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
